
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StarsCanvas from "@/components/sub/StarBackground";


const exo = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Justin Santos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={exo.className}>
      <StarsCanvas/>
        {children}</body>
    </html>

  );
}
